node:
    image: node
    ports:
        - "3030:3030"
    volumes:
        - /home/docker/workspace/StackRealtime/app-realtime:/usr/src/app
    links:
        - redis:redis
    command: node /usr/src/app/index.js

redis:
    image: redis
    ports:
        - "6379:6379"